# Generated by Django 2.1.11 on 2020-01-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0060_auto_20200128_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='countdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
