# Generated by Django 2.2.16 on 2020-09-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0063_auto_20200206_1432'),
        ('barsys', '0059_invoice_payment_link'),
    ]

    operations = [
    ]
